steps:
# Docker build
  - name: 'gcr.io/cloud-builders/docker:latest'
    args: ['build','--network=cloudbuild', '-t', 'europe-west1-docker.pkg.dev/${PROJECT_ID}/docker-repository/salary-predict:${SHORT_SHA}', '.']
 # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker:latest'
    args: ['push',  'europe-west1-docker.pkg.dev/angelswing-research/docker-repository/salary-predict:${SHORT_SHA}']
images: ['europe-west1-docker.pkg.dev/angelswing-research/docker-repository/salary-predict:${SHORT_SHA}']
timeout: 3600s
options:
  logging: CLOUD_LOGGING_ONLY

